/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts_perpus;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALAN
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        judul = new javax.swing.JTextField();
        no = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        novel = new javax.swing.JRadioButton();
        bacaan = new javax.swing.JRadioButton();
        pelajaran = new javax.swing.JRadioButton();
        tgl_kembali = new com.toedter.calendar.JDateChooser();
        tgl_pinjam = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        print = new javax.swing.JButton();
        save = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamat_peminjam = new javax.swing.JTextArea();
        status = new javax.swing.JTextField();
        print1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("FORM PENGEMBALIAN BUKU PERPUSTAKAAN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, -30, 910, 130);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Status");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 490, 110, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("No Anggota");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 80, 110, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nama Peminjam");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 130, 130, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Alamat Peminjam");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 180, 160, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Jenis Buku");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 290, 110, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Judul Buku");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 340, 110, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Tanggal Pinjam");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 390, 150, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Tanggal Kembali");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 440, 150, 40);
        getContentPane().add(judul);
        judul.setBounds(140, 340, 170, 40);
        getContentPane().add(no);
        no.setBounds(140, 80, 170, 40);
        getContentPane().add(nama);
        nama.setBounds(140, 130, 170, 40);

        buttonGroup1.add(novel);
        novel.setText("Novel");
        getContentPane().add(novel);
        novel.setBounds(290, 300, 90, 23);

        buttonGroup1.add(bacaan);
        bacaan.setText("Bacaan");
        getContentPane().add(bacaan);
        bacaan.setBounds(140, 300, 70, 23);

        buttonGroup1.add(pelajaran);
        pelajaran.setText("Pelajaran");
        getContentPane().add(pelajaran);
        pelajaran.setBounds(210, 300, 100, 23);
        getContentPane().add(tgl_kembali);
        tgl_kembali.setBounds(140, 440, 170, 40);
        getContentPane().add(tgl_pinjam);
        tgl_pinjam.setBounds(140, 390, 170, 40);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No Anggota", "Nama Peminjam", "Alamat Peminjam", "Jenis Buku", "Judul Buku", "Tanggal Pinjam", "Tanggal Kembali", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Long.class, java.lang.Long.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabel);
        if (tabel.getColumnModel().getColumnCount() > 0) {
            tabel.getColumnModel().getColumn(0).setResizable(false);
            tabel.getColumnModel().getColumn(1).setResizable(false);
            tabel.getColumnModel().getColumn(2).setResizable(false);
            tabel.getColumnModel().getColumn(3).setResizable(false);
            tabel.getColumnModel().getColumn(4).setResizable(false);
            tabel.getColumnModel().getColumn(5).setResizable(false);
            tabel.getColumnModel().getColumn(6).setResizable(false);
            tabel.getColumnModel().getColumn(7).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(390, 130, 890, 402);

        print.setText("REFRESH");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print);
        print.setBounds(1170, 80, 110, 40);

        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(390, 80, 80, 40);

        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(480, 80, 80, 40);

        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(570, 80, 80, 40);

        alamat_peminjam.setColumns(20);
        alamat_peminjam.setRows(5);
        jScrollPane2.setViewportView(alamat_peminjam);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(140, 190, 166, 96);
        getContentPane().add(status);
        status.setBounds(140, 490, 170, 40);

        print1.setText("PRINT");
        print1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print1ActionPerformed(evt);
            }
        });
        getContentPane().add(print1);
        print1.setBounds(660, 80, 80, 40);

        setSize(new java.awt.Dimension(1329, 627));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:        
        if("".equals(no.getText()) || "".equals(nama.getText()) || "".equals(alamat_peminjam.getText()) || "".equals(judul.getText()) || "".equals(tgl_pinjam) || "".equals(tgl_kembali) || "".equals(status.getText()))
        {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } 
        else
        {   
            String jenis = "";
                if(bacaan.isSelected()){
                    jenis = "Bacaan";
                } else if(pelajaran.isSelected()){
                    jenis = "Pelajaran";
                } else if(novel.isSelected()){
                    jenis = "Novel";
                }
            String SQL = "INSERT INTO tb_pengembalian (NoAnggota,NamaPeminjam,AlamatPeminjam,JenisBuku,JudulBuku,tgl_pinjam,tgl_kembali,status)" + "VALUES('" + no.getText()+"','"+ nama.getText()+"','"+ alamat_peminjam.getText()+"','"+ jenis +"','"+ judul.getText()+"','"+ tgl_pinjam.getDate() +"','"+ tgl_kembali.getDate() +"','"+ status.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if(status==1){
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else{
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_saveActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        no.setText("");
        nama.setText("");
        alamat_peminjam.setText("");
        buttonGroup1.clearSelection();
        judul.setText("");
        tgl_pinjam.setCalendar(null);
        tgl_kembali.setCalendar(null);
        status.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_printActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int baris = tabel.getSelectedRow();
       if (baris != -1){
           String NoAnggota = tabel.getValueAt(baris, 0).toString();
           String SQL = "DELETE FROM tb_pengembalian WHERE NoAnggota='"+NoAnggota+"'";
           int status = KoneksiDB.execute(SQL);
           if(status==1){
               JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
           } else{
               JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
           }
       } else{
           JOptionPane.showMessageDialog(this, "Pilih Baris Terlebih Dahulu", "Error", JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_deleteActionPerformed

    private void print1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print1ActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Data Perpustakaan");
        MessageFormat footer = new MessageFormat("Page (0,number,integer)       ");
        try{
            tabel.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_print1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat_peminjam;
    private javax.swing.JRadioButton bacaan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField judul;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField no;
    private javax.swing.JRadioButton novel;
    private javax.swing.JRadioButton pelajaran;
    private javax.swing.JButton print;
    private javax.swing.JButton print1;
    private javax.swing.JButton save;
    private javax.swing.JTextField status;
    private javax.swing.JTable tabel;
    private com.toedter.calendar.JDateChooser tgl_kembali;
    private com.toedter.calendar.JDateChooser tgl_pinjam;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"NoAnggota","NamaPeminjam","AlamatPeminjam","JenisBuku","JudulBuku","tgl_pinjam","tgl_kembali","status"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_pengembalian";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while(rs.next()){
                String NoAnggota = rs.getString(1);
                String NamaPeminjam = rs.getString(2);
                String AlamatPeminjam = rs.getString(3);
                String JenisBuku = "";
                if("Bacaan".equals(rs.getString(4))) {
                    JenisBuku = "Bacaan";
                } else{
                    JenisBuku = "Pelajaran";
                } 
                String JudulBuku = rs.getString(5);
                String tgl_pinjam = rs.getString(6);
                String tgl_kembali = rs.getString(7);
                String status = rs.getString(8);
                String data[] = {NoAnggota,NamaPeminjam,AlamatPeminjam,JenisBuku,JudulBuku,tgl_pinjam,tgl_kembali,status};
                dtm.addRow(data);
            }
        } catch(SQLException ex){
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        tabel.setModel(dtm);
    }
}

